### ISSUE TITLE
avoiding loops for shortening URLs

### ISSUE THREAD

**Issue by tusharnankani** [dheerajdlalwani/url-shortner#16]
- If I generate a shortened URL, and I copy it and I can keep generating a shortened URL.
- This can be easily avoided by simply adding by implementing a check here: 

```python
if "url-shortener-flask-mongodb.herokuapp.com" in long_url:
      message = "This URL is already shortened!" 
     return render_template('home.html', message=message) 
```

 https://github.com/dheerajdlalwani/url-shortener/blob/be97b2447ffbeb3e4aa1d377b00bfdc346aec83c/main.py#L16-L35

**Comment by dheerajdlalwani** [comment]
Hi Tushar! Thank you for raising this issue. The issue has now been fixed. Please do test it out and confirm here. Also the domain is updated: [Kata](https://kata-flask.herokuapp.com)
